/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_driftfxnative_application_App */

#ifndef _Included_com_driftfxnative_application_App
#define _Included_com_driftfxnative_application_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_driftfxnative_application_App
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_driftfxnative_application_App_nativeInit(JNIEnv *, jobject, jobject);
JNIEXPORT jlong JNICALL Java_com_driftfxnative_application_App_nativeOnStart(JNIEnv *, jobject, jobject, jobject);
JNIEXPORT void JNICALL Java_com_driftfxnative_application_App_nativeOnRender(JNIEnv *, jobject, long);

#ifdef __cplusplus
}
#endif
#endif
